name: Dependency-review

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '44 18 * * 1'

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 
      - name: Run Dependency Review
        uses: github/dependency-review-action@v2
        with:
          comment-summary: true
          allow-licenses: MIT, Apache-2.0, ISC, BSD-2-Clause, 0BSD, NOASSERTION
          base-ref: ${{ github.event.pull_request.base.sha || 'main' }}
          head-ref: ${{ github.event.pull_request.head.sha || github.ref }}