name: Dependency-review

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
  schedule:
    - cron: '44 18 * * 1'

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 
      - name: Run Dependency Review
        uses: github/dependency-review-action@v2
        with:
          comment-summary: true